"""Multi-pass gap detector.

Two passes shipped in Wave 1:

  Pass A — *intro-promise extraction*. The Introduction of a manuscript
           promises a set of topics, regions, named entities, or thesis
           claims that the reader expects later chapters to flesh out.
           We extract these with an LLM, then deterministically pair each
           promise to a real heading in the manuscript and decide whether
           that section is *empty* (tier 1, big gap) or *thin* (tier 2,
           small gap). Promises matched to a well-developed section
           (>300 words) are dropped — already covered.

  Pass B — *bracketed TODO extraction*. Pure regex over the body of the
           manuscript. The author's convention is `[note about a thing
           that needs research]`. Citation refs (`[Smith 2003]`, `[1]`)
           and one-word `[TODO]` markers are filtered out. Each surviving
           bracketed string becomes one tier-1 gap whose research_question
           is generated by a single-shot LLM rephrase.

Both functions return ``List[Dict]`` ready to feed into
``adapters.gap_tree.insert_node`` — they do not write to the DB themselves.

Helpers from ``layers.analysis`` are reused (``_extract_docx``,
``_split_sections``); that module is not modified.
"""

from __future__ import annotations

import math
import re
from collections import Counter
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from layers.analysis import _extract_docx, _split_sections


# ---------------------------------------------------------------------------
# Pass A — Intro-promise extraction
# ---------------------------------------------------------------------------

PASS_A_SYSTEM_PROMPT = """\
You are analyzing the Introduction of a history manuscript on e-commerce.
Extract every named topic, region, named entity, or thesis claim that the
author *promises to cover later in the book*. Each promise is something the
reader expects to see fleshed out in a chapter. Do NOT include topics
the introduction itself fully discusses.

For each promise, return:
- promise_text: the verbatim sentence or phrase from the intro (≤200 chars)
- key_entity: the most specific named subject (company, person, place, regulation)
- region: "US" | "China" | "India" | "Latin America" | "Europe" | "Africa" | "Global"
- expected_chapter_hint: 3-6 word guess at which chapter would cover this
- importance: 1-5 (5 = central thesis claim, 1 = passing reference)

Output STRICT JSON: a list of objects only. No prose, no fences.
"""

PASS_B_RQ_SYSTEM_PROMPT = """\
You are converting an author's terse TODO into a clear research question
that a librarian can use. Output ONE concise sentence."""


# Stop-words used by the cheap TF-IDF-style scorer in heading pairing.
# This is heading-pairing, not retrieval; aggressive stop-word stripping
# would over-prefer numbered chapter heads. Kept short on purpose.
_STOPWORDS = {
    "a", "an", "and", "as", "at", "be", "but", "by", "for", "if", "in",
    "into", "is", "it", "its", "of", "on", "or", "that", "the", "to",
    "was", "were", "with", "from", "this", "these", "those", "have",
    "has", "had", "are", "we", "you", "i", "our", "their", "his", "her",
    "they", "she", "he", "do", "does", "did", "not", "no", "yes",
    "chapter", "section",
}


def _tokenize(text: str) -> List[str]:
    """Lowercase + alphanumeric + drop stopwords for pairing scorer."""
    if not text:
        return []
    raw = re.findall(r"[a-zA-Z0-9]+", text.lower())
    return [w for w in raw if w not in _STOPWORDS and len(w) > 2]


def _extract_introduction(text: str) -> Tuple[str, List[Dict[str, Any]]]:
    """Return (introduction_text, all_sections).

    The Introduction is the first section whose heading contains
    "Introduction" (case-insensitive). The section ends at the next heading
    whose text starts with "Chapter" — or at the next section, whichever
    comes first if the manuscript has no chapter markers (e.g. tests).

    Returns ("", sections) if no Introduction is found.
    """
    sections = _split_sections(text)

    intro_idx: Optional[int] = None
    for i, sec in enumerate(sections):
        heading = sec.get("heading", "")
        if "introduction" in heading.lower():
            intro_idx = i
            break

    if intro_idx is None:
        return "", sections

    # Walk forward from intro until we hit a heading starting with "Chapter".
    # If no such heading is ever found, just return the intro section's body.
    accum_lines: List[str] = list(sections[intro_idx].get("lines", []))
    for j in range(intro_idx + 1, len(sections)):
        next_heading = sections[j].get("heading", "")
        if next_heading.lower().startswith("chapter"):
            break
        # Otherwise this is a sub-heading still inside the intro region —
        # include its body in the intro text. (Per spec: "the section under
        # the first heading containing 'Introduction' up to (but not
        # including) the next heading whose text starts with 'Chapter'".)
        accum_lines.extend(sections[j].get("lines", []))

    intro_text = " ".join(accum_lines).strip()
    return intro_text, sections


def _heading_word_counts(sections: List[Dict[str, Any]]) -> Dict[str, int]:
    """Return {heading: body_word_count} for every section."""
    out: Dict[str, int] = {}
    for sec in sections:
        heading = sec.get("heading", "")
        body = " ".join(sec.get("lines", [])).strip()
        out[heading] = len(body.split())
    return out


def _score_heading_for_promise(
    promise_text: str,
    key_entity: str,
    region: str,
    heading: str,
) -> float:
    """Deterministic similarity score between a promise and a heading.

    Score components:
      +2.0  substring match of *key_entity* (case-insensitive) in heading
      +1.0  substring match of *region* in heading
      0..+1 cheap word-overlap of promise_text vs heading

    The result is in roughly [0, 4]. Caller picks the top-scoring heading.
    """
    score = 0.0
    h_low = heading.lower().strip()

    if key_entity and key_entity.strip().lower() in h_low:
        score += 2.0

    if region and region.strip().lower() in h_low and region.strip().lower() != "global":
        score += 1.0

    # Word overlap — Counter intersection over a tiny vocabulary.
    p_tokens = Counter(_tokenize(promise_text))
    h_tokens = Counter(_tokenize(heading))
    if p_tokens and h_tokens:
        overlap = sum((p_tokens & h_tokens).values())
        denom = max(1, math.sqrt(sum(p_tokens.values()) * sum(h_tokens.values())))
        score += min(1.0, overlap / denom)

    return score


def _classify_promise_tier(body_word_count: int) -> Optional[Tuple[int, int]]:
    """Decide tier and evidence_target from how developed the section is.

    Returns (tier, evidence_target), or None if the section is already
    well-developed and the promise should be SKIPPED.
    """
    if body_word_count < 80:
        return (1, 120)
    if body_word_count <= 300:
        return (2, 60)
    return None  # >300 words → already covered


def _research_question_for_promise(
    promise: Dict[str, Any],
    matched_heading: str,
    llm: Any,
) -> str:
    """Ask the LLM for a one-sentence research question for an intro promise.

    Falls back to the verbatim promise_text if the LLM call errors or
    returns nothing useful. The caller decides whether to retry.
    """
    promise_text = (promise.get("promise_text") or "").strip()
    key_entity = (promise.get("key_entity") or "").strip()
    if not promise_text:
        return ""
    user = (
        f"Promise from the manuscript Introduction:\n  \"{promise_text}\"\n"
        f"Key entity: {key_entity or '(none)'}\n"
        f"Expected chapter: {matched_heading or '(unknown)'}\n\n"
        "Convert this promise into ONE concise research question a "
        "librarian could use to find scholarly sources. Reply with only "
        "the question."
    )
    try:
        out = llm.complete(system=PASS_B_RQ_SYSTEM_PROMPT, prompt=user, temperature=0.1)
        return re.sub(r"\s+", " ", (out or "").strip()).strip('"').strip()[:400]
    except Exception:
        return promise_text[:400]


def detect_pass_a(
    docx_path: Path,
    llm: Any,
    *,
    formatter_llm: Optional[Any] = None,
) -> List[Dict[str, Any]]:
    """Pass A: extract intro promises and classify them as tier-1 / tier-2 gaps.

    Returns a list of dicts ready for ``adapters.gap_tree.insert_node``:

        {
          "gap_id":           "IP1",
          "tier":             1 or 2,
          "gap_type":         "intro_promise",
          "chapter":          <matched heading>,
          "heading_path":     <matched heading>,
          "claim_text":       <verbatim promise sentence>,
          "research_question":<LLM-derived 1-sentence question>,
          "source_locator":   "introduction",
          "evidence_target":  120 or 60,
          "detector_pass":    "A",
          "rationale":        "<explanation of why kept>",
        }

    The empty list is returned if the manuscript has no Introduction
    section, or if the LLM produces no parseable promises.
    """
    # Local import — defer the heavy dependency until needed and avoid
    # circular imports if score_relevance ever imports this module.
    from scripts.score_relevance import repair_json_with_fallback  # noqa: WPS433

    text = _extract_docx(Path(docx_path))
    intro_text, sections = _extract_introduction(text)
    if not intro_text:
        return []

    user_prompt = (
        "Manuscript Introduction (verbatim):\n\n"
        f"{intro_text[:12000]}\n\n"
        "Return the JSON array of promises now."
    )

    parsed: Any = None
    try:
        parsed = llm.complete_json(
            system=PASS_A_SYSTEM_PROMPT,
            prompt=user_prompt,
            temperature=0.1,
        )
    except Exception:
        parsed = None

    if not isinstance(parsed, list):
        # Repair pathway — request raw and pass through the formatter LLM.
        try:
            raw = llm.complete(
                system=PASS_A_SYSTEM_PROMPT,
                prompt=user_prompt,
                temperature=0.1,
            )
        except Exception:
            raw = ""
        parsed = repair_json_with_fallback(raw or "", formatter_llm) or []

    if not isinstance(parsed, list) or not parsed:
        return []

    word_counts = _heading_word_counts(sections)
    headings = list(word_counts.keys())

    out: List[Dict[str, Any]] = []
    ip_index = 0

    for promise in parsed:
        if not isinstance(promise, dict):
            continue
        promise_text = (promise.get("promise_text") or "").strip()
        if not promise_text:
            continue
        key_entity = (promise.get("key_entity") or "").strip()
        region = (promise.get("region") or "").strip()

        # Pair with the best-matching heading. If no heading scores > 0,
        # skip the promise — pairing is required for downstream review.
        if not headings:
            continue
        best_heading: Optional[str] = None
        best_score = -1.0
        for h in headings:
            if not h or h.lower().startswith("introduction"):
                # Skip the intro itself — promises always point forward.
                continue
            sc = _score_heading_for_promise(promise_text, key_entity, region, h)
            if sc > best_score:
                best_score = sc
                best_heading = h
        if best_heading is None or best_score <= 0:
            continue

        body_wc = word_counts.get(best_heading, 0)
        cls = _classify_promise_tier(body_wc)
        if cls is None:
            # Section already developed — skip per spec.
            continue
        tier, evidence_target = cls

        ip_index += 1
        gap_id = f"IP{ip_index}"

        rq = _research_question_for_promise(
            promise={"promise_text": promise_text, "key_entity": key_entity},
            matched_heading=best_heading,
            llm=llm,
        )

        rationale = (
            f"Pairing score={best_score:.2f}; matched section body={body_wc} words"
            + (f"; importance={promise.get('importance')}" if promise.get("importance") else "")
        )

        out.append({
            "gap_id":            gap_id,
            "tier":              tier,
            "gap_type":          "intro_promise",
            "chapter":           best_heading,
            "heading_path":      best_heading,
            "claim_text":        promise_text[:600],
            "research_question": rq,
            "source_locator":    "introduction",
            "evidence_target":   evidence_target,
            "detector_pass":     "A",
            "rationale":         rationale,
        })

    return out


# ---------------------------------------------------------------------------
# Pass B — Bracketed TODO extraction
# ---------------------------------------------------------------------------

# Match bracketed strings whose content (after leading whitespace) starts
# with a letter, length 5-300. Length floor 10 + "must contain a space"
# filter applied post-match below. Real manuscript TODOs sometimes start
# with leading spaces (``[       MORE ON THIS PLEASE]``) so we tolerate
# whitespace before the first letter.
_BRACKET_RE = re.compile(r"\[\s*([A-Za-z][^\]]{4,300})\]", re.DOTALL)


def _looks_like_citation(content: str) -> bool:
    """Filter out citation-style brackets like [Smith 2003] or [Bezos, 2013].

    Heuristic: short content (<= 4 words) that ends with a 4-digit year.
    The actual `[1]` numeric refs and `[Smith 2003]` are also filtered by
    the >=10 char and "must contain a space" rules below — this is an
    additional safety net for short author-year citations.
    """
    words = content.split()
    if len(words) <= 4 and re.search(r"\b(18|19|20)\d{2}\b", content):
        return True
    return False


def _evidence_target_for_todo(content: str) -> int:
    """40 if the TODO is ≤6 words (narrow gap), 80 otherwise (build-a-section)."""
    n_words = len(content.split())
    return 40 if n_words <= 6 else 80


def detect_pass_b(
    docx_path: Path,
    *,
    llm: Optional[Any] = None,
    conn: Optional[Any] = None,
) -> List[Dict[str, Any]]:
    """Pass B: regex over the manuscript body for bracketed TODOs.

    Returns dicts ready for ``insert_node``. Each TODO becomes one tier-1
    gap with ``gap_type='explicit_todo'``. The research_question is
    LLM-generated when an *llm* is supplied; if a *conn* is also supplied,
    we resume — re-running won't re-call the LLM for TODOs whose
    ``research_question`` is already populated in the DB.

    The *llm* parameter is optional so unit tests can run pure regex
    without a model. Production callers always pass one.
    """
    # Lazy imports keep the module tree-import-light.
    from adapters.gap_tree import fetch_research_question  # noqa: WPS433

    text = _extract_docx(Path(docx_path))
    sections = _split_sections(text)

    # Build a (heading, body_text) sweep so we can tag each TODO with chapter.
    # Each section's body is rejoined as one block for matching; line-level
    # split would split a multi-line bracketed TODO across matches.
    todos: List[Tuple[str, str]] = []  # (chapter_heading, content)
    seen: set = set()

    # Track which section heading is the most recent "real" chapter so that
    # bracket-shaped pseudo-headings (e.g. ``[HOW DID IT GET TO EBAY]``) get
    # tagged with their parent chapter rather than themselves.
    last_real_chapter = "Manuscript Body"

    for sec in sections:
        heading = sec.get("heading", "Manuscript Body")
        body = " ".join(sec.get("lines", []))

        # Some bracketed TODOs get promoted to section headings by
        # _split_sections (when they're ALLCAPS short lines). Those would
        # otherwise be invisible because they don't appear in any section
        # body. Detect them at heading scope and route to the previous
        # real chapter.
        head_match = _BRACKET_RE.match(heading)
        if head_match:
            content = head_match.group(1).strip()
            if (
                len(content) >= 10
                and " " in content
                and not _looks_like_citation(content)
            ):
                key = (last_real_chapter, content.lower())
                if key not in seen:
                    seen.add(key)
                    todos.append((last_real_chapter, content))
            # heading was a TODO — do NOT update last_real_chapter
        else:
            # This heading is a real chapter/section name; remember it.
            last_real_chapter = heading

        for m in _BRACKET_RE.finditer(body):
            content = m.group(1).strip()
            # Length floor (>=10) and "must contain a space" filter
            if len(content) < 10:
                continue
            if " " not in content:
                continue
            if _looks_like_citation(content):
                continue
            # Dedupe identical bracketed strings within the run.
            key = (last_real_chapter, content.lower())
            if key in seen:
                continue
            seen.add(key)
            todos.append((last_real_chapter, content))

    out: List[Dict[str, Any]] = []
    for i, (heading, content) in enumerate(todos, start=1):
        gap_id = f"TODO{i}"
        evidence_target = _evidence_target_for_todo(content)

        # Resume-safe: if the row is already in the DB and has a
        # research_question, reuse it without calling the LLM.
        rq: Optional[str] = None
        if conn is not None:
            rq = fetch_research_question(conn, gap_id)

        if not rq and llm is not None:
            try:
                user = (
                    f"Author's bracketed TODO from the manuscript:\n"
                    f"  \"{content}\"\n\n"
                    "Convert this terse note into ONE concise research "
                    "question that a librarian could use to find scholarly "
                    "sources. Reply with only the question."
                )
                resp = llm.complete(
                    system=PASS_B_RQ_SYSTEM_PROMPT,
                    prompt=user,
                    temperature=0.1,
                )
                rq = re.sub(r"\s+", " ", (resp or "").strip()).strip('"').strip()[:400]
            except Exception:
                rq = None
        if not rq:
            # Fallback: use the verbatim TODO as the research question.
            rq = content[:400]

        out.append({
            "gap_id":            gap_id,
            "tier":              1,
            "gap_type":          "explicit_todo",
            "chapter":           heading,
            "heading_path":      heading,
            "claim_text":        content[:600],
            "research_question": rq,
            "source_locator":    "manuscript_body",
            "evidence_target":   evidence_target,
            "detector_pass":     "B",
            "rationale":         f"bracketed TODO; {len(content.split())} words",
        })

    return out
