#!/usr/bin/env python3
"""Wave 2 entry point: pull documents for every gap_tree node.

Reads ``gap_tree`` from ``data/article_index.sqlite`` and runs the
per-gap-type query plan + dispatch pipeline. Resume-safe (status='pulled'
rows are skipped).

Usage:
  python3 scripts/pull_gap_tree.py --tier 1
  python3 scripts/pull_gap_tree.py --gap-ids CP23,IP1 --run-id wave2-smoke
  python3 scripts/pull_gap_tree.py --dry-run

Defaults:
  --run-id        gaptree_<YYYYMMDDhhmm>  (autogenerated when omitted)
  --db            data/article_index.sqlite
  --model         llama3.1:8b              (query rewrites)
  --pull-root     data/pull_outputs/<run_id>
  --tier          (none — all pullable tiers)

Telegram notifications (per AGENTS.md §15):
  - On run start: "Wave 2 pull starting — N gaps in scope"
  - After each gap completes: gap id + record count
  - On completion / error
"""

from __future__ import annotations

import argparse
import json
import os
import sqlite3
import sys
import time
import traceback
import urllib.parse
import urllib.request
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
sys.path.insert(0, str(PROJECT_ROOT))

# Load .env so ORCH_* / EBSCO_* / TELEGRAM_* are available.
_env_path = PROJECT_ROOT / ".env"
if _env_path.exists():
    for _line in _env_path.read_text().splitlines():
        _line = _line.strip()
        if _line and not _line.startswith("#") and "=" in _line:
            k, v = _line.split("=", 1)
            os.environ.setdefault(k.strip(), v.strip())

from adapters.gap_tree import ensure_gap_tree_schema  # noqa: E402
from adapters.sec_edgar import DEFAULT_USER_AGENT as SEC_UA  # noqa: E402
from config import OrchestratorSettings  # noqa: E402
from layers.gap_query_planner import plan_queries  # noqa: E402
from layers.llm_client import make_llm_client  # noqa: E402
from layers.pull_dispatch import fetch_pullable_nodes, pull_gap  # noqa: E402

DEFAULT_DB = PROJECT_ROOT / "data" / "article_index.sqlite"


# ---------------------------------------------------------------------------
# Telegram helpers (per AGENTS.md §15)
# ---------------------------------------------------------------------------


def _load_telegram_creds() -> Optional[Dict[str, str]]:
    """Load Telegram credentials from ~/.claude/settings.json (or None)."""
    settings_path = Path.home() / ".claude" / "settings.json"
    if not settings_path.exists():
        return None
    try:
        env = json.loads(settings_path.read_text(encoding="utf-8")).get("env", {})
    except Exception:
        return None
    token = env.get("TELEGRAM_BOT_TOKEN")
    chat = env.get("TELEGRAM_CHAT_ID")
    if not token or not chat:
        return None
    return {"token": token, "chat": str(chat)}


def _telegram_send(creds: Optional[Dict[str, str]], msg: str) -> None:
    """Best-effort Telegram send. Silent on failure; never raises."""
    if not creds:
        return
    try:
        body = urllib.parse.urlencode(
            {"chat_id": creds["chat"], "text": msg}
        ).encode()
        urllib.request.urlopen(
            urllib.request.Request(
                f"https://api.telegram.org/bot{creds['token']}/sendMessage",
                data=body,
            ),
            timeout=10,
        )
    except Exception:
        pass


# ---------------------------------------------------------------------------
# Browser bootstrap (CDP-attached Chrome)
# ---------------------------------------------------------------------------


def _open_browser_page(settings: Any) -> Any:
    """Connect to the user's already-running CDP Chrome and open a tab.

    Mirrors the pattern in scripts/pull_proquest_newspapers.py — we reuse
    the existing context (assumes JHU EZproxy session is live in there).
    """
    from playwright.sync_api import sync_playwright

    from adapters.cdp_utils import effective_cdp_url

    cdp_url = getattr(settings, "playwright_cdp_url", "http://127.0.0.1:9222")
    pw = sync_playwright().__enter__()
    browser = pw.chromium.connect_over_cdp(effective_cdp_url(cdp_url))
    ctx = browser.contexts[0] if browser.contexts else browser.new_context()
    page = ctx.new_page()
    # Restore user's tab so we don't hold focus on their workstation.
    try:
        others = [p for p in ctx.pages if p is not page]
        if others:
            others[0].bring_to_front()
    except Exception:
        pass
    return pw, browser, ctx, page


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def _autogen_run_id() -> str:
    return "gaptree_" + datetime.now().strftime("%Y%m%d%H%M")


def main() -> int:
    p = argparse.ArgumentParser(description="Pull documents for gap_tree nodes (Wave 2).")
    p.add_argument("--db", default=str(DEFAULT_DB), help="SQLite DB path.")
    p.add_argument("--run-id", default=None,
                   help="Run ID for output dir. Default: gaptree_<YYYYMMDDhhmm>.")
    p.add_argument("--tier", type=int, default=None,
                   help="Only pull gaps at this tier (1, 2, ...).")
    p.add_argument("--gap-ids", default=None,
                   help="Comma-separated gap_ids to pull (overrides --tier).")
    p.add_argument("--model", default="llama3.1:8b",
                   help="LLM model used for query rewrites. Default llama3.1:8b.")
    p.add_argument("--pull-root", default=None,
                   help="Override pull_outputs root (default data/pull_outputs/<run_id>).")
    p.add_argument("--dry-run", action="store_true",
                   help="Print plan only; don't pull.")
    p.add_argument("--no-telegram", action="store_true",
                   help="Suppress Telegram notifications.")
    p.add_argument("--no-browser", action="store_true",
                   help="Skip browser open (HathiTrust + ProQuest pulls become no-ops).")
    p.add_argument("--include-pulled", action="store_true",
                   help="Re-run pulls on gaps already at status='pulled'.")
    args = p.parse_args()

    run_id = args.run_id or _autogen_run_id()
    db_path = Path(args.db)
    pull_root = Path(args.pull_root) if args.pull_root else (
        PROJECT_ROOT / "data" / "pull_outputs" / run_id
    )
    pull_root.mkdir(parents=True, exist_ok=True)

    creds = None if args.no_telegram else _load_telegram_creds()

    conn = sqlite3.connect(str(db_path))
    conn.row_factory = sqlite3.Row
    ensure_gap_tree_schema(conn)

    gap_ids: Optional[List[str]] = None
    if args.gap_ids:
        gap_ids = [g.strip() for g in args.gap_ids.split(",") if g.strip()]

    nodes = fetch_pullable_nodes(
        conn, tier=args.tier, gap_ids=gap_ids,
        include_pulled=args.include_pulled,
    )

    print(f"DB: {db_path}", flush=True)
    print(f"Run ID: {run_id}", flush=True)
    print(f"Pull root: {pull_root}", flush=True)
    print(f"Pullable gaps in scope: {len(nodes)}", flush=True)

    if not nodes:
        print("Nothing to pull. Exiting.", flush=True)
        return 0

    settings = OrchestratorSettings.from_env()
    llm = make_llm_client(
        settings, model=args.model,
        timeout_seconds=120, temperature=0.2,
    )

    # ---- dry-run: print the plan and exit
    if args.dry_run:
        for node in nodes:
            plans = plan_queries(dict(node), llm)
            print(f"\n[{node['gap_id']}] tier={node['tier']} "
                  f"type={node['gap_type']} "
                  f"claim={(node['claim_text'] or '')[:80]}")
            for q, src in plans:
                print(f"  → {src}: {q[:90]}")
        return 0

    # ---- live pull
    pw_handle = browser = ctx = page = None
    if not args.no_browser:
        try:
            pw_handle, browser, ctx, page = _open_browser_page(settings)
        except Exception as exc:
            print(f"[warn] browser open failed: {exc!s:.150}", flush=True)
            page = None

    _telegram_send(
        creds,
        f"Wave 2 pull starting — {len(nodes)} gaps in scope (run_id={run_id}).",
    )

    total_records = 0
    successes: List[str] = []
    failures: List[str] = []

    try:
        for i, node in enumerate(nodes, 1):
            gap_id = node["gap_id"]
            print(f"\n[{i}/{len(nodes)}] {gap_id} "
                  f"tier={node['tier']} type={node['gap_type']}", flush=True)
            t0 = time.time()
            try:
                result = pull_gap(
                    conn, dict(node),
                    run_id=run_id,
                    llm=llm,
                    pull_root=pull_root,
                    page=page,
                    sec_user_agent=SEC_UA,
                )
            except Exception as exc:
                tb = traceback.format_exc()
                print(f"[error] {gap_id}: {exc!s:.150}\n{tb[:600]}", flush=True)
                failures.append(gap_id)
                _telegram_send(creds, f"[Wave 2] {gap_id} crashed: {exc!s:.120}")
                continue

            dt = time.time() - t0
            n = result["records_pulled"]
            total_records += n
            if result.get("skipped"):
                print(f"  ↳ skipped ({result.get('reason')})", flush=True)
                continue

            if result["errors"]:
                failures.append(gap_id)
            else:
                successes.append(gap_id)

            print(
                f"  ↳ {n} records across {len(result['sources_used'])} sources "
                f"in {dt:.1f}s; status={result.get('status')}",
                flush=True,
            )
            _telegram_send(
                creds,
                f"[Wave 2] {gap_id}: {n} records, "
                f"sources={','.join(result['sources_used'])}, "
                f"status={result.get('status')}",
            )

    finally:
        if page is not None:
            try:
                page.close()
            except Exception:
                pass
        if pw_handle is not None:
            try:
                pw_handle.__exit__(None, None, None)
            except Exception:
                pass
        conn.close()

    print(f"\n=== summary ===", flush=True)
    print(f"  gaps successful: {len(successes)}", flush=True)
    print(f"  gaps with errors: {len(failures)}", flush=True)
    print(f"  total records pulled: {total_records}", flush=True)

    _telegram_send(
        creds,
        f"[Wave 2] DONE. {len(successes)} ok, {len(failures)} errs, "
        f"{total_records} records (run {run_id}).",
    )

    return 0


if __name__ == "__main__":
    sys.exit(main())
